import type { Metadata } from "next";
// import { Inter } from "next/font/google";  <-- COMMENT THIS OUT
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] }); <-- COMMENT THIS OUT

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Remove className={inter.className} from the body tag below */}
      <body>{children}</body>
    </html>
  );
}
